image: rust:latest

stages:
- test
- deploy

# Use cargo to test the project
test cargo stable:
  stage: test
  script:
  - rustc --version && cargo --version      # Print version info for debugging
  - cargo test --all --verbose
  - cargo test --all --no-default-features

test cargo 1.34:
  image: rust:1.34.0
  stage: test
  script:
  - rustc --version && cargo --version
  - cargo run --example enums

#deploy:crates.io:
#  image: registry.gitlab.com/torkleyy/cargo-publish-all:latest
#  stage: deploy
#  script:
#  - cargo-publish-all --token $CRATES_IO_TOKEN --yes
#  only:
#    refs:
#    - main
