connectionUrl: unix:///srv/luminous-dynamics/_websites/mycelix.net/holochain/socket?k=EfYxt4zmQPthZQu_G4PUtAxDOGK1hmlZBq9YEn02I1s

# The pid file for managing a running lair-keystore process
pidFile: /srv/luminous-dynamics/_websites/mycelix.net/holochain/pid_file

# The sqlcipher store file for persisting secrets
storeFile: /srv/luminous-dynamics/_websites/mycelix.net/holochain/store_file

# Configuration for managing sign_by_pub_key fallback
# in case the pub key does not exist in the lair store.
# - `signatureFallback: none`
# - ```
#   signatureFallback: !command
#     # 'program' will resolve to a path, specifying 'echo'
#     # will try to run './echo', probably not what you want.
#     program: "./my-executable"
#     # args are optional
#     args:
#       - test-arg1
#       - test-arg2
#   ```
signatureFallback: none

# -- cryptographic secrets --
# If you modify the data below, you risk losing access to your keys.
databaseSalt: Sgf4g5NMJln0tSznLYn1Rg
runtimeSecretsSalt: 3oKHQP_YY4nWnefmzGacNQ
runtimeSecretsMemLimit: 268435456
runtimeSecretsOpsLimit: 3
runtimeSecretsContextKey:
- 0aov6HTMDHNmM_IyZNhdxqgiVTYUWNNv
- ug-cKdyBDt8QBb2Sp5GZZGpSvaB1hCHSbNqa5t569C3z5m1KT8EJfRP4ESuvpx54Zw
runtimeSecretsIdSeed:
- wjWExR1BYvVRXNEPDH3L8uIFfj4TkXwG
- l-QUa5s58--LFNbTbv7Tu9Ny0ZzJFP_Kk0tc1voOqtLTVkjZxdTxLVgUj0sK-TNcJQ
